### ISSUE TITLE
help with automater

### ISSUE THREAD

**Issue by laniidae** [zk4/epub2html#7]
automater
source ~/.bash_profile
/Library/Frameworks/Python.framework/Versions/3.9/bin/epub2html "$1"

error
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.9/bin/epub2html", line 8, in <module>
sys.exit(entry_point())
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/epub2html/epub2html.py", line 228, in entry_point
main(mainArgs)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/epub2html/epub2html.py", line 206, in main
if filepath[0]!="." and filepath[0]!="/":
IndexError: string index out of range

**Comment by laniidae** [comment]
/Library/Frameworks/Python.framework/Versions/3.9/bin/epub2html xx.epub
works for me in bash

**Comment by zk4** [comment]
It seems $1 did not get any filepath.
